name       : git
version    : 2.18.0
release    : 70
source     :
    - https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.18.0.tar.xz : 8b40be383a603147ae29337136c00d1c634bdfdc169a30924a024596a7e30e92
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : programming.tools
summary    : fast, scalable, distributed revision control system
description: |
    Git is a fast, scalable, distributed revision control system with an
    unusually rich command set that provides both high-level operations
    and full access to internals.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - asciidoc
    - xmlto
    - perl-error
patterns   :
    - /usr/share/man
rundeps    :
    - perl-authen-sasl
    - perl-error
    - perl-io
    - perl-io-socket-ssl
    - perl-libnet
    - perl-mime-base64
    - perl-net-smtp-ssl
    - perl-net-ssleay
    - tk
setup      : |
    %configure --disable-static
build      : |
    %make all doc
    cd contrib/subtree
    %make
install    : |
    %make_install install-doc
    cd contrib/subtree
    %make_install install-doc
    cd $workdir
    # Bash completion
    install -Dm00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
    install -Dm00644 contrib/completion/git-prompt.sh $installdir/%libdir%/git/git-core/git-sh-prompt
check      : |
    %make test
