name       : git
version    : 2.20.1
release    : 81
source     :
    - https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz : 9d2e91e2faa2ea61ba0a70201d023b36f54d846314591a002c610ea2ab81c3e9
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : programming.tools
summary    : fast, scalable, distributed revision control system
description: |
    Git is a fast, scalable, distributed revision control system with an
    unusually rich command set that provides both high-level operations
    and full access to internals.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libnghttp2)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh2)
    - pkgconfig(krb5)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - asciidoc
    - xmlto
    - perl-error
patterns   :
    - /usr/share/man
rundeps    :
    - nano
    - perl-authen-sasl
    - perl-error
    - perl-io
    - perl-io-socket-ssl
    - perl-libnet
    - perl-mime-base64
    - perl-net-smtp-ssl
    - perl-net-ssleay
    - tk
setup      : |
    %configure --disable-static --with-editor=/usr/bin/nano
build      : |
    %make all doc
    cd contrib/subtree
    %make
    cd $workdir/contrib/credential/libsecret
    %make
install    : |
    %make_install install-doc
    cd contrib/subtree
    %make_install install-doc
    cd $workdir
    # Bash completion
    install -Dm00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
    install -Dm00644 contrib/completion/git-prompt.sh $installdir/%libdir%/git/git-core/git-sh-prompt
    # Credential helper
    install -Dm00755 contrib/credential/libsecret/git-credential-libsecret $installdir/%libdir%/git/git-core/git-credential-libsecret
    # git-archive-all, used in most Solus tarball generation scripts
    install -Dm00755 $pkgfiles/git-archive-all $installdir/usr/bin/git-archive-all
check      : |
    # These tests failed on the server
    export GIT_SKIP_TESTS="t5562.9 t5562.16"
    %make test
