name       : git
version    : 2.8.4
release    : 34
source     :
    - https://www.kernel.org/pub/software/scm/git/git-2.8.4.tar.xz : 120e9a32a1858871dea34165622ec7a63f27887b93093c8d72a18bcf89fe1657
license    : GPL-2.0
component  : programming.tools
summary    : fast, scalable, distributed revision control system
description: |
    fast, scalable, distributed revision control system
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - asciidoc
    - xmlto
    - perl-error
patterns   :
    - /usr/share/man
rundeps    :
    - perl-authen-sasl
    - perl-error
    - perl-io
    - perl-io-socket-ssl
    - perl-libnet
    - perl-mime-base64
    - perl-net-smtp-ssl
    - perl-net-ssleay
setup      : |
    %configure --disable-static
build      : |
    %make all doc
install    : |
    %make_install install-doc
    # Bash completion
    install -D -m 00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
