name       : git
version    : 2.19.2
release    : 77
source     :
    - https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.19.2.tar.xz : fce9a3a3297db5f3756c4553a2fc1fec209ee08178f8491e76ff4ff8fe7b8be9
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : programming.tools
summary    : fast, scalable, distributed revision control system
description: |
    Git is a fast, scalable, distributed revision control system with an
    unusually rich command set that provides both high-level operations
    and full access to internals.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libsecret-1)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - asciidoc
    - xmlto
    - perl-error
patterns   :
    - /usr/share/man
rundeps    :
    - perl-authen-sasl
    - perl-error
    - perl-io
    - perl-io-socket-ssl
    - perl-libnet
    - perl-mime-base64
    - perl-net-smtp-ssl
    - perl-net-ssleay
    - tk
setup      : |
    %configure --disable-static
build      : |
    %make all doc
    cd contrib/subtree
    %make
    cd $workdir/contrib/credential/libsecret
    %make
install    : |
    %make_install install-doc
    cd contrib/subtree
    %make_install install-doc
    cd $workdir
    # Bash completion
    install -Dm00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
    install -Dm00644 contrib/completion/git-prompt.sh $installdir/%libdir%/git/git-core/git-sh-prompt
    # Credential helper
    install -Dm00755 contrib/credential/libsecret/git-credential-libsecret $installdir/%libdir%/git/git-core/git-credential-libsecret
check      : |
    # These tests failed on the server
    export GIT_SKIP_TESTS="t5562.9 t5562.16"
    %make test
