name        : git
version     : 2.7.3
release     : 27
source     :
    - https://www.kernel.org/pub/software/scm/git/git-2.7.3.tar.gz : 30d067499b61caddedaf1a407b4947244f14d10842d100f7c7c6ea1c288280cd
license     : GPL-2.0
summary     : fast, scalable, distributed revision control system 
builddeps   :
    - pkgconfig(zlib)
    - pkgconfig(openssl)
patterns    :
    - /usr/share/man
rundeps     :
    - perl-io-socket-ssl
    - perl-io
    - perl-net-ssleay
    - perl-net-smtp-ssl
    - perl-libnet
    - perl-error
    - perl-mime-base64
    - perl-authen-sasl
description : |
    fast, scalable, distributed revision control system
setup      : |
    %patch -p1 < $pkgfiles/stop_using_name_patch.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Bash completion
    install -D -m 00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
