name       : git
version    : 2.40.0
release    : 116
source     :
    - https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.40.0.tar.xz : b17a598fbf58729ef13b577465eb93b2d484df1201518b708b5044ff623bf46d
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : programming.tools
homepage   : https://git-scm.com/
summary    : fast, scalable, distributed revision control system
description: |
    Git is a fast, scalable, distributed revision control system with an
    unusually rich command set that provides both high-level operations
    and full access to internals.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libpcre2-8)
    - pkgconfig(libsecret-1)
    - asciidoc
    - xmlto
    - perl-error
patterns   :
    - /usr/share/man
rundeps    :
    - nano
    - perl-authen-sasl
    - perl-error
    - perl-io-socket-ssl
    - tk
setup      : |
    %patch -p1 < $pkgfiles/0001-t-test-lib.sh-Don-t-clobber-LD_PRELOAD-if-already-se.patch
    %configure --disable-static \
               --with-editor=/usr/bin/nano \
               --with-libpcre2
build      : |
    %make all doc
    cd contrib/subtree
    %make
    cd $workdir/contrib/credential/libsecret
    %make
install    : |
    %make_install install-doc
    cd contrib/subtree
    %make_install install-doc
    cd $workdir
    # Bash completion
    install -Dm00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
    install -Dm00644 contrib/completion/git-prompt.sh $installdir/%libdir%/git/git-core/git-sh-prompt
    # Zsh completion
    install -Dm00644 contrib/completion/git-completion.zsh $installdir/usr/share/zsh/site-functions/_git
    # Credential helper
    install -Dm00755 contrib/credential/libsecret/git-credential-libsecret $installdir/%libdir%/git/git-core/git-credential-libsecret
    # git-archive-all, used in most Solus tarball generation scripts
    install -Dm00755 $pkgfiles/git-archive-all $installdir/usr/bin/git-archive-all
check      : |
    # These tests failed on the server
    export GIT_SKIP_TESTS="t5562.9 t5562.16 t1301 t5324.29"
    %make test
