name        : git
version     : 2.6.2
release     : 21
source     :
    - https://github.com/git/git/archive/v2.6.2.tar.gz : 5107c308ebb693cfa09a434745ef35261af36df5aa35435694804af445ede630
license     : GPL-2.0
summary     : fast, scalable, distributed revision control system 
builddeps   :
    - pkgconfig(zlib)
    - pkgconfig(openssl)
patterns    :
    - /usr/share/man
rundeps     :
    - perl-io-socket-ssl
    - perl-io
    - perl-net-ssleay
    - perl-net-smtp-ssl
    - perl-libnet
    - perl-error
    - perl-mime-base64
    - perl-authen-sasl
description : |
    fast, scalable, distributed revision control system
setup      : |
    make configure
    %configure
build      : |
    %make
install    : |
    %make_install
    # Bash completion
    install -D -m 00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
