name        : git
version     : 2.6.4
release     : 23
source     :
    - https://github.com/git/git/archive/v2.6.4.tar.gz : 08e3ccdba87ca55140c8155a07e147f6c1cdd7b574690e960763b18474fd05ed
license     : GPL-2.0
summary     : fast, scalable, distributed revision control system 
builddeps   :
    - pkgconfig(zlib)
    - pkgconfig(openssl)
patterns    :
    - /usr/share/man
rundeps     :
    - perl-io-socket-ssl
    - perl-io
    - perl-net-ssleay
    - perl-net-smtp-ssl
    - perl-libnet
    - perl-error
    - perl-mime-base64
    - perl-authen-sasl
description : |
    fast, scalable, distributed revision control system
setup      : |
    make configure
    %configure
build      : |
    %make
install    : |
    %make_install
    # Bash completion
    install -D -m 00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
