name       : git
version    : 2.14.2
release    : 56
source     :
    - https://www.kernel.org/pub/software/scm/git/git-2.14.2.tar.xz : 50e9723996114ad1eec4dda89960d9fe34461749ae42031008a261fedd03c7a1
license    : GPL-2.0
component  : programming.tools
summary    : fast, scalable, distributed revision control system
description: |
    Git is a fast, scalable, distributed revision control system with an
    unusually rich command set that provides both high-level operations
    and full access to internals.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(openssl)
    - pkgconfig(zlib)
    - asciidoc
    - xmlto
    - perl-error
patterns   :
    - /usr/share/man
rundeps    :
    - perl-authen-sasl
    - perl-error
    - perl-io
    - perl-io-socket-ssl
    - perl-libnet
    - perl-mime-base64
    - perl-net-smtp-ssl
    - perl-net-ssleay
setup      : |
    %configure --disable-static
build      : |
    %make all doc
    cd contrib/subtree
    %make
install    : |
    %make_install install-doc
    cd contrib/subtree
    %make_install install-doc
    cd $workdir
    # Bash completion
    install -D -m 00644 contrib/completion/git-completion.bash $installdir/usr/share/bash-completion/completions/git
